#!/usr/bin/env python3
"""Generate Visual Studio files for HelloCustomWidgets.

The project is a Makefile project, so the generated configurations only select
APP_SUB and build flavor. Actual compilation still goes through the repository
root Makefile.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from xml.sax.saxutils import escape


REPO_ROOT = Path(__file__).resolve().parents[2]
PROJECT_GUID = "{AA3090DF-1484-473C-A87D-5E381BDCD05F}"
SOLUTION_GUID = "{BDBBFA23-8331-47B0-A30A-9D067B52FA1E}"
CATALOG_PATH = REPO_ROOT / "example" / "HelloCustomWidgets" / "widget_catalog.json"
PROJECT_PATH = REPO_ROOT / "vs" / "HelloCustomWidgets.vcxproj"
SOLUTION_PATH = REPO_ROOT / "EmbeddedGUI_Widgets.sln"


@dataclass(frozen=True)
class VsCase:
    app_sub: str
    config_stem: str


def xml(value: str) -> str:
    return escape(value, {'"': "&quot;"})


def read_cases() -> list[VsCase]:
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    app_subs = ["showcase"]
    app_subs.extend(item["id"] for item in catalog)

    seen: set[str] = set()
    cases: list[VsCase] = []
    for app_sub in app_subs:
        if app_sub in seen:
            raise ValueError(f"duplicate APP_SUB in catalog: {app_sub}")
        seen.add(app_sub)

        app_sub_path = REPO_ROOT / "example" / "HelloCustomWidgets" / app_sub
        if not (app_sub_path / "test.c").exists():
            raise FileNotFoundError(f"missing test.c for APP_SUB={app_sub}")

        stem = "HCW_" + app_sub.replace("/", "_").replace("\\", "_")
        cases.append(VsCase(app_sub=app_sub, config_stem=stem))

    return cases


def all_configurations(cases: list[VsCase]) -> list[tuple[str, str]]:
    configs: list[tuple[str, str]] = [("Debug", "Debug"), ("Release", "Release")]
    for case in cases:
        configs.append((f"{case.config_stem}_Debug", "Debug"))
        configs.append((f"{case.config_stem}_Release", "Release"))
    return configs


def write_text(path: Path, text: str) -> None:
    with path.open("w", encoding="utf-8", newline="\r\n") as handle:
        handle.write(text)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate Visual Studio files for HelloCustomWidgets.")
    return parser.parse_args()


def render_project(cases: list[VsCase]) -> str:
    configs = all_configurations(cases)
    project_configs = "\n".join(
        [
            f'    <ProjectConfiguration Include="{xml(config)}|x64">\n'
            f"      <Configuration>{xml(config)}</Configuration>\n"
            "      <Platform>x64</Platform>\n"
            "    </ProjectConfiguration>"
            for config, _ in configs
        ]
    )

    named_configs: list[str] = []
    for case in cases:
        for flavor in ("Debug", "Release"):
            config = f"{case.config_stem}_{flavor}"
            named_configs.append(
                f'    <EguiAppSub Condition="\'$(Configuration)\'==\'{xml(config)}\'">{xml(case.app_sub)}</EguiAppSub>'
            )

    named_config_block = "\n".join(named_configs)

    return f"""<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Generated by scripts/vs/generate_vs_configs.py. -->
  <ItemGroup Label="ProjectConfigurations">
{project_configs}
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <VCProjectVersion>17.0</VCProjectVersion>
    <Keyword>MakeFileProj</Keyword>
    <ProjectGuid>{PROJECT_GUID}</ProjectGuid>
    <RootNamespace>HelloCustomWidgets</RootNamespace>
    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.Default.props" />
  <PropertyGroup>
    <PlatformToolset Condition="'$(PlatformToolset)'=='' And Exists('$(VCTargetsPath)\\Platforms\\$(Platform)\\PlatformToolsets\\v145\\Toolset.props')">v145</PlatformToolset>
    <PlatformToolset Condition="'$(PlatformToolset)'=='' And Exists('$(VCTargetsPath)\\Platforms\\$(Platform)\\PlatformToolsets\\v143\\Toolset.props')">v143</PlatformToolset>
    <PlatformToolset Condition="'$(PlatformToolset)'=='' And Exists('$(VCTargetsPath)\\Platforms\\$(Platform)\\PlatformToolsets\\v142\\Toolset.props')">v142</PlatformToolset>
  </PropertyGroup>
  <PropertyGroup>
    <EguiBuildFlavor Condition="'$(Configuration)'=='Debug'">Debug</EguiBuildFlavor>
    <EguiBuildFlavor Condition="'$(Configuration)'=='Release'">Release</EguiBuildFlavor>
    <EguiBuildFlavor Condition="'$(EguiBuildFlavor)'=='' And $([System.String]::Copy('$(Configuration)').EndsWith('_Debug'))">Debug</EguiBuildFlavor>
    <EguiBuildFlavor Condition="'$(EguiBuildFlavor)'=='' And $([System.String]::Copy('$(Configuration)').EndsWith('_Release'))">Release</EguiBuildFlavor>
  </PropertyGroup>
  <PropertyGroup Condition="'$(EguiBuildFlavor)'=='Debug'" Label="Configuration">
    <ConfigurationType>Makefile</ConfigurationType>
    <UseDebugLibraries>true</UseDebugLibraries>
  </PropertyGroup>
  <PropertyGroup Condition="'$(EguiBuildFlavor)'=='Release'" Label="Configuration">
    <ConfigurationType>Makefile</ConfigurationType>
    <UseDebugLibraries>false</UseDebugLibraries>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings" />
  <ImportGroup Label="Shared" />
  <ImportGroup Label="PropertySheets" Condition="'$(Platform)'=='x64'">
    <Import Project="$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <EguiRepoRoot>$(MSBuildThisFileDirectory)..\\</EguiRepoRoot>
    <EguiSdkRoot>$(EguiRepoRoot)sdk\\EmbeddedGUI\\</EguiSdkRoot>
    <EguiScript>$(EguiRepoRoot)scripts\\vs\\vs_make.ps1</EguiScript>
    <EguiApp>HelloCustomWidgets</EguiApp>
    <EguiAppSub Condition="'$(EguiAppSub)'==''">showcase</EguiAppSub>
    <EguiPort>pc</EguiPort>
  </PropertyGroup>
  <PropertyGroup Label="EmbeddedGUI Named App Configurations">
{named_config_block}
  </PropertyGroup>
  <PropertyGroup>
    <EguiOutputSuffix Condition="'$(EguiOutputSuffix)'==''">$([System.String]::Copy('$(EguiAppSub)').Replace('\\', '_').Replace('/', '_'))</EguiOutputSuffix>
    <EguiOutputDir>$(EguiRepoRoot)output\\vs\\$(EguiApp)\\$(EguiOutputSuffix)\\$(Configuration)\\</EguiOutputDir>
    <EguiAppPath>$(EguiRepoRoot)example\\HelloCustomWidgets</EguiAppPath>
    <EguiAppSubPath>$(EguiAppPath)\\$(EguiAppSub)</EguiAppSubPath>
    <OutDir>$(EguiOutputDir)</OutDir>
    <IntDir>$(EguiRepoRoot)output\\vs\\obj\\$(EguiApp)\\$(EguiOutputSuffix)\\$(Configuration)\\</IntDir>
    <NMakeBuildCommandLine>powershell -NoProfile -ExecutionPolicy Bypass -File &quot;$(EguiScript)&quot; -Action build -App $(EguiApp) -AppSub &quot;$(EguiAppSub)&quot; -Port $(EguiPort) -Configuration &quot;$(Configuration)&quot;</NMakeBuildCommandLine>
    <NMakeReBuildCommandLine>powershell -NoProfile -ExecutionPolicy Bypass -File &quot;$(EguiScript)&quot; -Action rebuild -App $(EguiApp) -AppSub &quot;$(EguiAppSub)&quot; -Port $(EguiPort) -Configuration &quot;$(Configuration)&quot;</NMakeReBuildCommandLine>
    <NMakeCleanCommandLine>powershell -NoProfile -ExecutionPolicy Bypass -File &quot;$(EguiScript)&quot; -Action clean -App $(EguiApp) -AppSub &quot;$(EguiAppSub)&quot; -Port $(EguiPort) -Configuration &quot;$(Configuration)&quot;</NMakeCleanCommandLine>
    <NMakeOutput>$(EguiOutputDir)main.exe</NMakeOutput>
    <NMakeIncludeSearchPath>$(EguiRepoRoot)example;$(EguiAppPath);$(EguiAppSubPath);$(EguiAppSubPath)\\resource;$(EguiAppSubPath)\\resource\\font;$(EguiAppSubPath)\\resource\\img;$(EguiSdkRoot)src;$(EguiSdkRoot)src\\widget;$(EguiSdkRoot)driver\\bus;$(EguiSdkRoot)driver\\lcd;$(EguiSdkRoot)driver\\touch;$(EguiSdkRoot)porting\\pc;$(EguiSdkRoot)porting\\pc\\sdl2\\64\\include;$(EguiSdkRoot)third_party\\file_image;$(EguiSdkRoot)third_party\\plutosvg\\source;$(EguiSdkRoot)third_party\\plutovg\\include</NMakeIncludeSearchPath>
    <NMakePreprocessorDefinitions Condition="'$(EguiBuildFlavor)'=='Debug'">_DEBUG;_CRT_SECURE_NO_WARNINGS;EGUI_APP=&quot;HelloCustomWidgets&quot;;EGUI_PORT=EGUI_PORT_TYPE_PC;EGUI_CONFIG_PLATFORM_CUSTOM_PRINTF=1;EGUI_PC_LOG_TO_DEBUG_OUTPUT=1;EGUI_PC_DEFAULT_DEBUG_LOG_LEVEL=3;PLUTOVG_BUILD_STATIC=1;PLUTOSVG_BUILD_STATIC=1</NMakePreprocessorDefinitions>
    <NMakePreprocessorDefinitions Condition="'$(EguiBuildFlavor)'=='Release'">NDEBUG;_CRT_SECURE_NO_WARNINGS;EGUI_APP=&quot;HelloCustomWidgets&quot;;EGUI_PORT=EGUI_PORT_TYPE_PC;EGUI_CONFIG_PLATFORM_CUSTOM_PRINTF=1;EGUI_PC_LOG_TO_DEBUG_OUTPUT=1;PLUTOVG_BUILD_STATIC=1;PLUTOSVG_BUILD_STATIC=1</NMakePreprocessorDefinitions>
    <LocalDebuggerCommand>$(NMakeOutput)</LocalDebuggerCommand>
    <LocalDebuggerWorkingDirectory>$(EguiOutputDir)</LocalDebuggerWorkingDirectory>
    <LocalDebuggerDebuggerType>NativeOnly</LocalDebuggerDebuggerType>
    <DebuggerFlavor>WindowsLocalDebugger</DebuggerFlavor>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\\Makefile" />
    <None Include="..\\example\\HelloCustomWidgets\\build.mk" />
    <None Include="..\\example\\HelloCustomWidgets\\widget_catalog.json" />
    <None Include="..\\scripts\\vs\\generate_vs_configs.py" />
    <None Include="..\\scripts\\vs\\vs_make.ps1" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets" />
</Project>
"""


def render_solution(cases: list[VsCase]) -> str:
    configs = all_configurations(cases)
    solution_configs = "\n".join(
        [f"\t\t{config}|x64 = {config}|x64" for config, _ in configs]
    )
    project_configs = "\n".join(
        [
            f"\t\t{PROJECT_GUID}.{config}|x64.ActiveCfg = {config}|x64\n"
            f"\t\t{PROJECT_GUID}.{config}|x64.Build.0 = {config}|x64"
            for config, _ in configs
        ]
    )

    return f"""Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.0.31903.59
MinimumVisualStudioVersion = 10.0.40219.1
Project("{{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}}") = "HelloCustomWidgets", "vs\\HelloCustomWidgets.vcxproj", "{PROJECT_GUID}"
EndProject
Global
\tGlobalSection(SolutionConfigurationPlatforms) = preSolution
{solution_configs}
\tEndGlobalSection
\tGlobalSection(ProjectConfigurationPlatforms) = postSolution
{project_configs}
\tEndGlobalSection
\tGlobalSection(SolutionProperties) = preSolution
\t\tHideSolutionNode = FALSE
\tEndGlobalSection
\tGlobalSection(ExtensibilityGlobals) = postSolution
\t\tSolutionGuid = {SOLUTION_GUID}
\tEndGlobalSection
EndGlobal
"""


def main() -> int:
    parse_args()
    cases = read_cases()
    write_text(PROJECT_PATH, render_project(cases))
    write_text(SOLUTION_PATH, render_solution(cases))
    print(f"Generated {len(cases)} HelloCustomWidgets cases")
    print(f"Wrote {PROJECT_PATH.relative_to(REPO_ROOT)}")
    print(f"Wrote {SOLUTION_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (FileNotFoundError, ValueError, json.JSONDecodeError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        raise SystemExit(1)
