#ifndef _HELLO_CUSTOM_WIDGETS_PALETTE_H_
#define _HELLO_CUSTOM_WIDGETS_PALETTE_H_

#include "egui.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Demo-level palette aligned with the SDK button theme. */
#define HCW_COLOR_PRIMARY          EGUI_THEME_PRIMARY
#define HCW_COLOR_PRIMARY_DARK     EGUI_THEME_PRIMARY_DARK
#define HCW_COLOR_PRIMARY_LIGHT    EGUI_THEME_PRIMARY_LIGHT
#define HCW_COLOR_PRIMARY_TINT     EGUI_COLOR_HEX(0x5EA2EF)
#define HCW_COLOR_PRIMARY_SOFT     EGUI_COLOR_HEX(0x4F95ED)
#define HCW_COLOR_ON_PRIMARY       EGUI_THEME_TEXT

#define HCW_COLOR_PAGE_BG          EGUI_THEME_SURFACE
#define HCW_COLOR_SURFACE          EGUI_THEME_SURFACE
#define HCW_COLOR_SURFACE_SUBTLE   EGUI_COLOR_HEX(0xF0F0F0)
#define HCW_COLOR_SURFACE_PRESS    EGUI_COLOR_HEX(0xE8E8E8)
#define HCW_COLOR_SURFACE_DISABLED EGUI_COLOR_HEX(0xE8E8E8)
#define HCW_COLOR_PANEL            EGUI_COLOR_HEX(0xFFFFFF)
#define HCW_COLOR_BORDER           EGUI_COLOR_HEX(0x5F6368)
#define HCW_COLOR_BORDER_STRONG    EGUI_COLOR_HEX(0x3C4043)
#define HCW_COLOR_TRACK            EGUI_COLOR_HEX(0x8A8A8A)
#define HCW_COLOR_TRACK_STRONG     EGUI_COLOR_HEX(0x5F6368)
#define HCW_COLOR_DISABLED         EGUI_THEME_DISABLED
#define HCW_COLOR_SHADOW           EGUI_THEME_TRACK_OFF

#define HCW_COLOR_TEXT             EGUI_THEME_TEXT_PRIMARY
#define HCW_COLOR_TEXT_STRONG      EGUI_THEME_TEXT_PRIMARY
#define HCW_COLOR_TEXT_MUTED       EGUI_THEME_TEXT_SECONDARY
#define HCW_COLOR_TEXT_SOFT        EGUI_COLOR_HEX(0x4B4B4B)

#define HCW_COLOR_SUCCESS          EGUI_THEME_SUCCESS
#define HCW_COLOR_SUCCESS_SOFT     EGUI_COLOR_HEX(0x6EE7A0)
#define HCW_COLOR_WARNING          EGUI_THEME_WARNING
#define HCW_COLOR_WARNING_SOFT     EGUI_COLOR_HEX(0xFCD34D)
#define HCW_COLOR_WARNING_DARK     EGUI_COLOR_HEX(0xB45309)
#define HCW_COLOR_DANGER           EGUI_THEME_DANGER
#define HCW_COLOR_DANGER_SOFT      EGUI_COLOR_HEX(0xF87171)
#define HCW_COLOR_DANGER_DARK      EGUI_COLOR_HEX(0xB91C1C)
#define HCW_COLOR_NEUTRAL          EGUI_COLOR_HEX(0x5F6368)

#ifdef __cplusplus
}
#endif

#endif /* _HELLO_CUSTOM_WIDGETS_PALETTE_H_ */
